import type { AppState } from "./types";

export function createSeedState(): AppState {
  return {
    coins: 12, // lower starting balance
    dogsRescued: 3,
    catsRescued: 2,
    walkStreak: 18,
    treatStreak: 6,
    speciesMode: "dog",
    activePetId: "dog-arlo",
    pets: [
      {
        id: "dog-arlo",
        species: "dog",
        name: "Arlo",
        breed: "Golden Retriever",
        birthday: "2023-04-12",
        bio: "Professional belly-rub enthusiast and part-time squirrel supervisor.",
        nicknames: ["Big Boy", "Sir Barks-a-lot", "Noodle"],
        personality: ["Goofy", "Affectionate", "Food-motivated", "Cuddly"],
        favoriteFoods: ["Peanut butter", "Roasted chicken", "Blueberries"],
        favoriteToys: ["Squeaky duck", "Tennis ball", "Rope tug"],
        health: 82,
        happiness: 88,
        cuddle: 24,
        neat: 15,
        level: 4,
        xp: 90,
        avatarEmoji: "🐶",
      },
      {
        id: "cat-regina",
        species: "cat",
        name: "Regina",
        breed: "British Longhair",
        birthday: "2022-11-03",
        bio: "Velvet-pawed sovereign of the sunbeam empire. Accepts tribute in tuna.",
        nicknames: ["Your Highness", "Mlle. Whiskers", "Queen Bee"],
        personality: ["Regal", "Curious", "Selective", "Affectionate (on her terms)"],
        favoriteFoods: ["Seared tuna", "Salmon flakes", "Catnip mousse"],
        favoriteToys: ["Feather wand", "Velvet mouse", "Crystal ball toy"],
        health: 90,
        happiness: 84,
        cuddle: 18,
        neat: 28,
        level: 5,
        xp: 72,
        avatarEmoji: "🐱",
      },
    ],
    memories: [
      {
        id: "m1",
        species: "dog",
        type: "achievement",
        title: "Learned to shake paws!",
        body: "Took three tries and one whole cheese stick, but he nailed it.",
        date: "2026-07-09",
        emoji: "🏆",
      },
      {
        id: "m2",
        species: "dog",
        type: "moment",
        title: "First snow zoomies",
        body: "Ran twelve laps around the yard the second it started snowing.",
        date: "2026-07-05",
        emoji: "💫",
      },
      {
        id: "m3",
        species: "dog",
        type: "photo",
        title: "Beach day nap",
        body: "Passed out mid-fetch, sandy paws and all.",
        date: "2026-06-27",
        emoji: "📸",
      },
      {
        id: "m4",
        species: "cat",
        type: "moment",
        title: "Claimed the velvet chaise",
        body: "A full coronation stretch. The court approved.",
        date: "2026-07-08",
        emoji: "👑",
      },
      {
        id: "m5",
        species: "cat",
        type: "achievement",
        title: "Perfect slow-blink exchange",
        body: "Diplomacy achieved. Treats followed.",
        date: "2026-07-02",
        emoji: "✨",
      },
    ],
    reminders: [
      {
        id: "r1",
        species: "dog",
        title: "Evening walk",
        note: "Sunset loop around the park",
        when: "today",
        done: false,
      },
      {
        id: "r2",
        species: "dog",
        title: "Dinner time",
        note: "1.5 cups + fish oil",
        when: "today",
        done: false,
      },
      {
        id: "r3",
        species: "dog",
        title: "Bath day",
        note: "Don't forget the oatmeal shampoo",
        when: "tomorrow",
        done: false,
      },
      {
        id: "r4",
        species: "cat",
        title: "Royal brushing",
        note: "Silk coat maintenance, 5 minutes",
        when: "today",
        done: false,
      },
      {
        id: "r5",
        species: "cat",
        title: "Dinner service",
        note: "Wet food + hydration fountain check",
        when: "today",
        done: false,
      },
      {
        id: "r6",
        species: "cat",
        title: "Litter refresh",
        note: "Throne room standards apply",
        when: "tomorrow",
        done: false,
      },
    ],
    earnings: [
      {
        id: "e1",
        label: "Daily check-in",
        amount: 2,
        at: new Date().toISOString().slice(0, 10),
        species: "dog",
      },
      {
        id: "e2",
        label: "Evening walk done",
        amount: 2,
        at: "2026-07-10",
        species: "dog",
      },
    ],
    achievements: [
      {
        id: "a1",
        species: "dog",
        title: "7-Day Walk Streak",
        description: "A full week of walkies!",
        emoji: "🦴",
        unlockedAt: "2026-06-21",
      },
      {
        id: "a2",
        species: "dog",
        title: "30-Day Walk Streak",
        description: "A whole month of adventures.",
        emoji: "🏆",
      },
      {
        id: "a3",
        species: "dog",
        title: "Bath Time Champion",
        description: "Survived bath day like a pro.",
        emoji: "🛁",
        unlockedAt: "2026-06-26",
      },
      {
        id: "a4",
        species: "cat",
        title: "Sunbeam Sovereign",
        description: "Claimed the best light in the house.",
        emoji: "☀️",
        unlockedAt: "2026-06-15",
      },
      {
        id: "a5",
        species: "cat",
        title: "Velvet Diplomat",
        description: "Perfected the slow blink.",
        emoji: "👑",
        unlockedAt: "2026-07-02",
      },
      {
        id: "a6",
        species: "cat",
        title: "Night Court Hunter",
        description: "Won five wand-toy battles.",
        emoji: "🌙",
      },
    ],
    familyTasks: [
      { id: "f1", owner: "mama", title: "Morning feeding", emoji: "🍚", done: false, species: "dog" },
      { id: "f2", owner: "mama", title: "Brush & cuddle", emoji: "🤗", done: false, species: "dog" },
      { id: "f3", owner: "papa", title: "Evening walk", emoji: "🦴", done: false, species: "dog" },
      { id: "f4", owner: "papa", title: "Fresh water & bowls", emoji: "💧", done: false, species: "dog" },
      { id: "f5", owner: "mama", title: "Breakfast service", emoji: "🐟", done: false, species: "cat" },
      { id: "f6", owner: "mama", title: "Royal brushing", emoji: "✨", done: false, species: "cat" },
      { id: "f7", owner: "papa", title: "Play decree", emoji: "🪶", done: false, species: "cat" },
      { id: "f8", owner: "papa", title: "Fountain & bowls", emoji: "💧", done: false, species: "cat" },
    ],
    adminStats: {
      totalUsers: 1284,
      charityRaisedUsd: 8420,
      dailyActive: 316,
    },
  };
}
